package com.ekdant.dentalsolution.register;
import com.ekdant.dentalsolution.dao.UserDao;
import com.ekdant.dentalsolution.domain.UserBean;
import javax.swing.JOptionPane;
import java.util.List;
/**
 *
 * @author Sushant
 */
public class RegisterUser extends javax.swing.JFrame {
    UserDao userDao;
    List<UserBean> users;
    int selectedUserIndex;
    /** Creates new form RegisterUser */
    public RegisterUser() {  
        userDao = new UserDao();
        initComponents();
        selectedUserIndex = 0;
        users = userDao.fetchAllUsers();
    }
    
    public void displayUser(UserBean user){
        userIdTxt.setText(""+user.getUserId());
        userNameTxt.setText(user.getName());
        userTxt.setText(user.getLoginId());
        passwordTxt.setText(user.getPassword());
        userTypeCB.setSelectedItem(user.getUserType());
    }

    public void populateUser(){
        if(users.size() > 0){
            displayUser(users.get(selectedUserIndex));
        }else{
             JOptionPane.showMessageDialog(null,"Could not update records", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        userTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        userTypeCB = new javax.swing.JComboBox();
        saveBtn = new javax.swing.JButton();
        userIdTxt = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        lastBtn = new javax.swing.JButton();
        firstBtn = new javax.swing.JButton();
        searchLbl = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Users");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("usuarios"); // NOI18N
        setResizable(false);

        nameLbl.setText("Name: ");

        userLbl.setText("User:");

        passwordLbl.setText("Password:");

        typeLbl.setText("Type:");

        userTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Employee", "Dentist" }));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Hygienist 1 Blue Check.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        userIdTxt.setEditable(false);
        userIdTxt.setMinimumSize(new java.awt.Dimension(0, 0));
        userIdTxt.setPreferredSize(new java.awt.Dimension(0, 0));

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Proximo_16x16.png"))); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        previousBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Anterior_16x16.png"))); // NOI18N
        previousBtn.setText("Previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        newBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Hygienist 1 Blue Add.png"))); // NOI18N
        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Hygienist 1 Blue Edit 2.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Hygienist 1 Blue Delete.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        lastBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Ultimo_16x16.png"))); // NOI18N
        lastBtn.setText("Last");
        lastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastBtnActionPerformed(evt);
            }
        });

        firstBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Primeiro_16x16.png"))); // NOI18N
        firstBtn.setText("First");
        firstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstBtnActionPerformed(evt);
            }
        });

        searchLbl.setText("Search :");

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EkDant/icones/Hygienist 1 Blue Search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl)
                            .addComponent(userLbl)
                            .addComponent(passwordLbl)
                            .addComponent(typeLbl))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(userTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(userTypeCB, 0, 194, Short.MAX_VALUE)
                        .addGap(272, 272, 272))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchLbl)
                        .addGap(18, 18, 18)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(previousBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLbl)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(userIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLbl)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLbl)
                    .addComponent(userTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(lastBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(previousBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        getAccessibleContext().setAccessibleName("usuarios");

        setSize(new java.awt.Dimension(579, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
        String name = userNameTxt.getText();
        String userId = userTxt.getText();
        String password = passwordTxt.getText();

        if (name.length() < 3) {
            JOptionPane.showMessageDialog(null, "Please enter your name!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else if (userId.length() < 3) {
            JOptionPane.showMessageDialog(null, "Please enter your username!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else if (userId.length() > 16) {
            JOptionPane.showMessageDialog(null, "Your username can not be more than 16 characters!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else if (duplicateUser(userId)) {
            JOptionPane.showMessageDialog(null, "The desired username is already taken!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your password!", "Attention", JOptionPane.WARNING_MESSAGE);

        } else if (password.length() > 8) {
            JOptionPane.showMessageDialog(null, "Your password can not be more than 8 characters", "Attention", JOptionPane.WARNING_MESSAGE);
        } else {

            UserBean user = new UserBean();
            user.setLoginId(userId);
            user.setPassword(password);
            user.setName(name);
            user.setUserType(userTypeCB.getSelectedItem().toString());

            if (userDao.addUser(user)) {
                JOptionPane.showMessageDialog(null, "User registered successfully!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                populateUser();
            } else {
                JOptionPane.showMessageDialog(null, "Could not register the user!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private boolean duplicateUser(String userId){
        return userDao.userPresent(userId);
    }
    
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        if(users.size() > selectedUserIndex){
            displayUser(users.get(++selectedUserIndex));
        }
        else{
             JOptionPane.showMessageDialog(null,"Oops! this is the last record!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        if(selectedUserIndex >= 1){
            displayUser(users.get(--selectedUserIndex));
        }
        else{
             JOptionPane.showMessageDialog(null,"Oops! This is the first record!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_previousBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        userIdTxt.setText("");
        userNameTxt.setText("");
        userTxt.setText("");
        passwordTxt.setText("");
        userTypeCB.setSelectedItem("Administrador");
        userNameTxt.requestFocus();
    }//GEN-LAST:event_newBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
        String userId = userIdTxt.getText();
        String name = userNameTxt.getText();
        String userName = userTxt.getText();
        String password = passwordTxt.getText();

        if (name.length() < 3) {
            JOptionPane.showMessageDialog(null, "Please enter your name!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else if (userName.length() < 3) {
            JOptionPane.showMessageDialog(null, "Please enter your username!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else if (userName.length() > 16) {
            JOptionPane.showMessageDialog(null, "Your username can not be more than 16 characters!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your password!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else if (password.length() > 8) {
            JOptionPane.showMessageDialog(null, "Your password can not be more than 8 characters", "Attention", JOptionPane.WARNING_MESSAGE);
        } else {
            UserBean user = new UserBean();
            user.setLoginId(userId);
            user.setPassword(password);
            user.setName(name);
            user.setUserType(userTypeCB.getSelectedItem().toString());

            if (userDao.updateUser(user)) {
                JOptionPane.showMessageDialog(null, "User successfully updated!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                populateUser();
            } else {
                JOptionPane.showMessageDialog(null, "Could not update user data! , ", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String userId = userIdTxt.getText();

        String confirmationMessage = "Really want to delete the user: " + userNameTxt.getText() + " ?";
        int chosenOption = JOptionPane.showConfirmDialog(null, confirmationMessage, "Delete", JOptionPane.YES_NO_OPTION);

        if (chosenOption == JOptionPane.YES_OPTION) {
            UserBean user = new UserBean();
            user.setUserId(Integer.parseInt(userId));
            if (userDao.deleteUser(user)) {
                JOptionPane.showMessageDialog(null, "User successfully deleted!", "Delete!", JOptionPane.INFORMATION_MESSAGE);
                populateUser();
            } else {
                JOptionPane.showMessageDialog(null, "Unable to delete user!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void lastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastBtnActionPerformed
        displayUser(users.get(users.size()));
    }//GEN-LAST:event_lastBtnActionPerformed

    private void firstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBtnActionPerformed
        displayUser(users.get(0));
        
    }//GEN-LAST:event_firstBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchString = searchTxt.getText();
        for(UserBean user : users){
            if(user.getName().equalsIgnoreCase(searchString)){
                displayUser(user);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton firstBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton lastBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton newBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton previousBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel typeLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField userIdTxt;
    private javax.swing.JLabel userLbl;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JTextField userTxt;
    private javax.swing.JComboBox userTypeCB;
    // End of variables declaration//GEN-END:variables
}