/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekdant.keygenerator;

import ekdant.main.AES;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.JOptionPane;

/**
 *
 * @author Sushant Raut
 */
public class KeyGeneratorMain extends javax.swing.JFrame {
    private static final DateFormat displayDateFormat = new SimpleDateFormat("dd-MMM-yyyy");
    

    /**
     * Creates new form KeyGeneratorMain
     */
    public KeyGeneratorMain() {
        initComponents();        
    }
    
    public void generateActivationFile() throws Exception{
        FileWriter fw =  null;//new FileWriter("D:\\Activation.key");
        java.util.Date today = new java.util.Date();
        if (motherboardSerialNumberTxt.getText().isEmpty() || activationSerialNumberTxt.getText().isEmpty() || activationDaysTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all fields!", "Attention", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Integer.parseInt(activationDaysTxt.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please enter valid activation days!", "Attention", JOptionPane.WARNING_MESSAGE);
                activationDaysTxt.requestFocus();
            }
            try {
                String validActivationFileKey = getValidString(UUID.randomUUID().toString());
                String validSerialNumber = getValidString(activationSerialNumberTxt.getText());
                String validMotherboardSN = getValidString(motherboardSerialNumberTxt.getText());
                String activationFileCreationDate = getValidString(displayDateFormat.format(today));
                String activationDays = getValidString(activationDaysTxt.getText());
                File activationFile = new File(activationDirectoryFC.getCurrentDirectory() + "//" + motherboardSerialNumberTxt.getText() + ".key");
                fw = new FileWriter(activationFile);
                fw.append(AES.getEncriptionString(validActivationFileKey) + "\n");
                fw.append(AES.getEncriptionString(validSerialNumber) + "\n");
                fw.append(AES.getEncriptionString(validMotherboardSN) + "\n");
                fw.append(AES.getEncriptionString(activationFileCreationDate) + "\n");
                fw.append(AES.getEncriptionString(activationDays) + "\n");
            } catch (IOException ex) {
            } catch (Exception ex) {
            } finally {
                try {
                    fw.close();
                } catch (IOException ex) {
                }
            }
        }
    }
    
    public static String getValidString(String str) {
        String validStringAppender = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";
        return (str + validStringAppender).substring(0, 16);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        activationSerialNumberLbl = new javax.swing.JLabel();
        motherboardSerialNumberLbl = new javax.swing.JLabel();
        activationDaysLbl = new javax.swing.JLabel();
        activationSerialNumberTxt = new javax.swing.JTextField();
        motherboardSerialNumberTxt = new javax.swing.JTextField();
        activationDaysTxt = new javax.swing.JTextField();
        activationDirectoryFC = new javax.swing.JFileChooser();
        generateBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Key File Generator");
        setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width,Toolkit.getDefaultToolkit().getScreenSize().height-Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration()).bottom));

        activationSerialNumberLbl.setText("Activation Serial Number*");

        motherboardSerialNumberLbl.setText("Motherboard Serial Number*");

        activationDaysLbl.setText("Activation Days*");

        activationDirectoryFC.setCurrentDirectory(new java.io.File("C:\\"));
            activationDirectoryFC.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

            generateBtn.setText("Generate File");
            generateBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    generateBtnActionPerformed(evt);
                }
            });

            resetBtn.setText("Reset");

            javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
            mainPanel.setLayout(mainPanelLayout);
            mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(activationSerialNumberLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(motherboardSerialNumberLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(activationDaysLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(motherboardSerialNumberTxt)
                                .addComponent(activationDaysTxt)
                                .addComponent(activationSerialNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(resetBtn)))
                    .addGap(18, 18, 18)
                    .addComponent(activationDirectoryFC, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            mainPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {activationDaysTxt, activationSerialNumberTxt, motherboardSerialNumberTxt});

            mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(activationSerialNumberLbl)
                                .addComponent(activationSerialNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(motherboardSerialNumberLbl)
                                .addComponent(motherboardSerialNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(activationDaysLbl)
                                .addComponent(activationDaysTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(resetBtn)))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(activationDirectoryFC, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            mainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {activationDaysLbl, activationDaysTxt, activationSerialNumberLbl, activationSerialNumberTxt, motherboardSerialNumberLbl, motherboardSerialNumberTxt});

            mainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {generateBtn, resetBtn});

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 459, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 195, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        try {
            generateActivationFile();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_generateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activationDaysLbl;
    private javax.swing.JTextField activationDaysTxt;
    private javax.swing.JFileChooser activationDirectoryFC;
    private javax.swing.JLabel activationSerialNumberLbl;
    private javax.swing.JTextField activationSerialNumberTxt;
    private javax.swing.JButton generateBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel motherboardSerialNumberLbl;
    private javax.swing.JTextField motherboardSerialNumberTxt;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
