/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekdant.keyreader;

import ekdant.main.AES;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Sushant Raut
 */
public class KeyReader extends javax.swing.JFrame {

    /**
     * Creates new form KeyReader
     */
    public KeyReader() {
        initComponents();
    }
    
    public void decryptAndReadActivationFile() {
        decryptAndReadActivationFile(activationFileFC.getSelectedFile());        
    }

    public void decryptAndReadActivationFile(File file) {
        StringBuilder activationFileContent = new StringBuilder();
        ArrayList<String> fileContent = new ArrayList();
        String line = null;
        try {
            FileReader activationFileReader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(activationFileReader);
            while ((line = bufferedReader.readLine()) != null) {
                fileContent.add(AES.decrypt(getByteArray(line)).trim());
            }
        } catch (FileNotFoundException ex) {System.out.println(ex.getMessage());} 
        catch (IOException ex) {System.out.println(ex.getMessage());} 
        catch (Exception ex) {System.out.println(ex.getMessage());}
        line1Lbl.setText("Activation File Key \t\t:" + fileContent.get(0));
        line2Lbl.setText("Activation Serial Number \t\t:" + fileContent.get(1));
        line3Lbl.setText("Activation Motherboard Number \t\t:" + fileContent.get(2));
        line4Lbl.setText("Activation Date \t\t:" + fileContent.get(3));
        line5Lbl.setText("Activation Days \t\t:" + fileContent.get(4));
    }
    
    public byte[] getByteArray(String string) {
        String str[] = string.split(" ");
        byte[] decryptedBytArr = new byte[str.length];

        for (int i = 0; i < str.length; i++) {
            decryptedBytArr[i] = new Byte(str[i]);
        }

        return decryptedBytArr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        activationFileFC = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        line1Lbl = new javax.swing.JLabel();
        line2Lbl = new javax.swing.JLabel();
        line3Lbl = new javax.swing.JLabel();
        line4Lbl = new javax.swing.JLabel();
        line5Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Read Activation File");
        setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width,Toolkit.getDefaultToolkit().getScreenSize().height-Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration()).bottom));

        activationFileFC.setCurrentDirectory(new java.io.File("C:\\"));

            jButton1.setText("Read");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            line1Lbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            line1Lbl.setForeground(new java.awt.Color(51, 51, 255));

            line2Lbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            line2Lbl.setForeground(new java.awt.Color(51, 51, 255));

            line3Lbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            line3Lbl.setForeground(new java.awt.Color(51, 51, 255));

            line4Lbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            line4Lbl.setForeground(new java.awt.Color(51, 51, 255));

            line5Lbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            line5Lbl.setForeground(new java.awt.Color(51, 51, 255));

            javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
            outputPanel.setLayout(outputPanelLayout);
            outputPanelLayout.setHorizontalGroup(
                outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(outputPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(line1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(line2Lbl)
                        .addComponent(line3Lbl)
                        .addComponent(line4Lbl)
                        .addComponent(line5Lbl))
                    .addContainerGap(24, Short.MAX_VALUE))
            );

            outputPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {line1Lbl, line2Lbl, line3Lbl, line4Lbl, line5Lbl});

            outputPanelLayout.setVerticalGroup(
                outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(outputPanelLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(line1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(line2Lbl)
                    .addGap(18, 18, 18)
                    .addComponent(line3Lbl)
                    .addGap(18, 18, 18)
                    .addComponent(line4Lbl)
                    .addGap(18, 18, 18)
                    .addComponent(line5Lbl)
                    .addContainerGap(126, Short.MAX_VALUE))
            );

            outputPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {line1Lbl, line2Lbl, line3Lbl, line4Lbl, line5Lbl});

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(activationFileFC, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(49, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(activationFileFC, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        decryptAndReadActivationFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser activationFileFC;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel line1Lbl;
    private javax.swing.JLabel line2Lbl;
    private javax.swing.JLabel line3Lbl;
    private javax.swing.JLabel line4Lbl;
    private javax.swing.JLabel line5Lbl;
    private javax.swing.JPanel outputPanel;
    // End of variables declaration//GEN-END:variables
}
