/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ekdant.dentalsolution.principal;

import com.ekdant.dentalsolution.dao.TokensDao;
import com.ekdant.dentalsolution.utilities.Activation;
import com.ekdant.dentalsolution.utilities.Utils;

/**
 *
 * @author Sushant Raut
 */
public class About extends javax.swing.JFrame {

    TokensDao tokensDao; 
    
    public About() {
        tokensDao = new TokensDao();
        initComponents();
        expirationDateLbl.setText("Your subscription validity is upto : " + tokensDao.fetchCurrentExpirationDate());
        serialNumberTxt.setText(Utils.getValidString(tokensDao.fetchSerialNumber()).trim()+"-"+Utils.getMotherboardSN());
//        if(!(Utils.demoVersion() || Utils.activationExpired())){
//            activationBtn.setVisible(false);
//        }
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versionTxt = new javax.swing.JLabel();
        userMessageTxt = new javax.swing.JLabel();
        activationBtn = new javax.swing.JButton();
        expirationDateLbl = new javax.swing.JLabel();
        serialNumberTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setResizable(false);

        versionTxt.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        versionTxt.setForeground(new java.awt.Color(51, 51, 255));
        versionTxt.setText("Version : 1.0.0");

        userMessageTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        userMessageTxt.setForeground(new java.awt.Color(51, 51, 255));
        userMessageTxt.setText("Please send us below serial Number on ekdantsoftware@gmail.com to get activation file");

        activationBtn.setText("Activate");
        activationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activationBtnActionPerformed(evt);
            }
        });

        expirationDateLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        expirationDateLbl.setForeground(new java.awt.Color(51, 51, 255));
        expirationDateLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        serialNumberTxt.setEditable(false);
        serialNumberTxt.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(versionTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userMessageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(expirationDateLbl)
                    .addComponent(serialNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 158, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {expirationDateLbl, serialNumberTxt, userMessageTxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(versionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(expirationDateLbl)
                .addGap(18, 18, 18)
                .addComponent(userMessageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(serialNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(activationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {expirationDateLbl, serialNumberTxt, userMessageTxt});

        setSize(new java.awt.Dimension(954, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void activationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activationBtnActionPerformed
        new Activation().setVisible(true);
    }//GEN-LAST:event_activationBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activationBtn;
    private javax.swing.JLabel expirationDateLbl;
    private javax.swing.JTextField serialNumberTxt;
    private javax.swing.JLabel userMessageTxt;
    private javax.swing.JLabel versionTxt;
    // End of variables declaration//GEN-END:variables

}
